spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwt_test
    username: root
    password: 1234
  jpa:
    show-sql: true


server:
  port: 8090
  
